
name: Run Test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
    
jobs:
  test-ios:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: swift package resolve
      
      - name: Start Xcode Build 🛠
        run: |
          xcodebuild clean test -project GloomyDiary.xcodeproj -scheme GloomyDiaryTests -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5'
